# Generated by Django 3.0.6 on 2020-05-21 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATName', models.CharField(max_length=200)),
                ('CATARName', models.CharField(default='product', max_length=200, verbose_name='إسم القسم بالعربي')),
                ('CATNSlug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='category Slug')),
            ],
            options={
                'verbose_name': 'صنف ',
                'verbose_name_plural': 'الاصناف ',
                'ordering': ('CATName',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODName', models.CharField(max_length=200, verbose_name='إسم المنتج')),
                ('PRODARName', models.CharField(default='product', max_length=200, verbose_name=' إسم المنتج عربي')),
                ('PRODSlug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Product Slug')),
                ('PRODDescription', models.TextField(verbose_name='وصف المنتج')),
                ('PRODCost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر شراء المنتج')),
                ('PRODPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر بيع المنتج')),
                ('PRODImage', models.ImageField(upload_to='Product-images', verbose_name='صور المنتج')),
                ('PRODAvailabel', models.BooleanField(default=True, verbose_name='هل المنتج موجود')),
                ('PRODQuantity', models.IntegerField(verbose_name='كمية المنتج ')),
                ('PRODCreated', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إضافة المنتج')),
                ('PRODUpdate', models.DateTimeField(auto_now=True, verbose_name='تاريخ تعديل المنتج')),
                ('PRODCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='')),
                ('PRODColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='لون المنتج')),
            ],
            options={
                'verbose_name': 'المنتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ('PRODName',),
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODimages', models.ImageField(upload_to='product-images', verbose_name='صور المنتج')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
