# Generated by Django 3.0.6 on 2020-05-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CATARName',
            field=models.CharField(max_length=200, verbose_name='إسم القسم بالعربي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRODColor',
            field=models.CharField(blank=True, choices=[('black', 'اسود'), ('white', 'ابيض'), ('red', 'احمر'), ('blue', 'ازرق')], max_length=50, verbose_name='لون المنتج'),
        ),
    ]
