# Generated by Django 3.0.6 on 2020-05-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200520_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PRODColor',
        ),
        migrations.AddField(
            model_name='productimages',
            name='PRODColor',
            field=models.CharField(blank=True, choices=[('black', 'اسود'), ('white', 'ابيض'), ('red', 'احمر'), ('blue', 'ازرق')], max_length=50, verbose_name='لون المنتج'),
        ),
    ]
