# Generated by Django 3.0.6 on 2020-05-23 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=200, verbose_name='الاسم بالكامل ')),
                ('PhoneNumber1', models.CharField(max_length=10, verbose_name='رقام الهاتف')),
                ('PhoneNumber2', models.CharField(blank=True, max_length=10, verbose_name='رقام هاتف اختياري')),
                ('ORDAddressEra', models.CharField(choices=[('', 'إختار الحي'), ('abushrif', 'ابو شريف م3'), ('square 31', 'مربع 31'), ('square 32', 'مربع 32'), ('square 29', 'مربع 29'), ('square 27', 'مربع 27'), ('square 26', 'مربع 26'), ('square 28', 'مربع 28'), ('square 34', 'مربع 34'), ('square 42', 'مربع 42'), ('square 43', 'مربع 42'), ('alandlos', 'الاندلس'), ('alnsry', 'النصري'), ('square 44', 'مربع 44'), ('square 39', 'مربع 39'), ('square 46', 'مربع 46'), ('square 47', 'مربع 47'), ('alhala ', 'الحلة الجديدة'), ('alshati', 'الشاطئ')], max_length=200, verbose_name=' المنطقة')),
                ('ORDAddress', models.TextField(verbose_name=' العنوان بالتفصيل')),
                ('ORDACreated', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('ORDAUpdate', models.DateTimeField(auto_now=True, verbose_name='تاريخ تعديل الطلب')),
                ('ORDPaid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'طلب المنتج',
                'verbose_name_plural': 'طلبات المنتجات',
                'ordering': ('-ORDACreated',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDIPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ORDIQuantity', models.PositiveIntegerField(default=1)),
                ('ORDIProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='order_items')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='items')),
            ],
        ),
    ]
