# Generated by Django 3.0.6 on 2020-05-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='PhoneNumber2',
            field=models.CharField(blank=True, max_length=10, verbose_name='رقام هاتف اختياري'),
        ),
    ]
